### ISSUE TITLE
Tasks requiring assistance?

### ISSUE THREAD

**Issue by rowanwins** [w8r/esri-leaflet-legend#2]
@w8r Just checking if you have any particular things you'd like me to assist with? Any documentation or examples etc?

**Comment by w8r** [comment]
@rowanwins thanks for the offer! Well, task is more or less done for the essential cases, I only wanted to make them really work with `FeatureLayer`s, grabbing renderers from metadata. Have to look into `esri-leaflet-renderers` to adapt their code for symbols from SVG to canvas. Then the whole picture would make sense

After that I could use some help with creating examples
