### ISSUE TITLE
Ensure compatibility with Leaflet 1.0

### ISSUE THREAD

**Issue by epos** [w8r/esri-leaflet-legend#3]
Leaflet 1.0 is out (http://leafletjs.com/2016/09/27/leaflet-1.0-final.html) but it seems this plugin is no compatible. I get the following error:

Cannot read property 'Util' of undefined esri-leaflet-legend.js:13

**Comment by w8r** [comment]
closed with the `2.0` release

**Comment by screamsyk** [comment]
you can change the way of importing it，like this:
`window.L = require('leaflet');
window.L.esri = require('esri-leaflet');
window.esriLeafletLegend = require('esri-leaflet-legend');`
because in the esri-leaflet-legend.js:
`if(typeof window !== 'undefined' && window.L){
    factory(window.L, L.esri);
  }`
